#!/bin/sh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:tlockney/dotfiles.git"

case "$(uname -s)" in
Darwin)
  echo "MacOS detected"

  command -v brew >/dev/null 2>&1 ||
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  test -f $HOME/.macos && sh $HOME/.macos

  test -f $HOME/.Brewfile && brew bundle --global

  if [ -x $HOME/.config/Code/User ]; then
    CODE_DIR=$HOME/.config/Code/User
    pushd $HOME/Library/Application\ Support/Code/User
    ln -sf $CODE_DIR/settings.json settings.json
    ln -sf $CODE_DIR/keybindings.json keybindings.json
    if [ -x "$PROFILE_DIR" ]; then
      pushd profiles/7db57729
      ln -sf $CODE_DIR/settings.json settings.json
      ln -sf $CODE_DIR/keybindings.json keybindings.json
      popd
    fi
    popd
  fi

  ;;

Linux)
  echo "Linux detected"
  echo "Installing packages with apt..."
  sudo apt-get update
  sudo apt-get install -y zsh tmux git

  if [ "$(basename "$SHELL")" != "zsh" ]; then
    echo "Setting zsh as the default shell"
    chsh -s $(which zsh)
  else
    echo "zsh is already the default shell"
  fi
  ;;
esac

if [ -x "$HOME/bin/sync-secrets" ]; then
  echo "\nRunning secret synchronization..."
  "$HOME/bin/sync-secrets"
else
  echo "\nWarning: sync-secrets script not found or not executable."
fi
