#!/bin/sh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:tlockney/dotfiles.git"

system_type=$(uname -s)

case "$(uname -s)" in
    Darwin)
	echo "MacOS detected"
	   # install homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
	    echo "Installing homebrew"
	    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
	if [ -f $HOME/.macos ]; then
	    sh $HOME/.macos
	fi
	if [ -f $HOME/.Brewfile ]; then
	    echo "Updating homebrew bundle"
	    brew bundle --global
	fi
	if [ -x $HOME/.config/Code/User ]; then
	    CODE_DIR=$HOME/.config/Code/User
	    pushd $HOME/Library/Application\ Support/Code/User
	    ln -sf $CODE_DIR/settings.json settings.json
	    ln -sf $CODE_DIR/keybindings.json keybindings.json
	    if [ -x "$PROFILE_DIR" ]; then
		pushd profiles/7db57729
		ln -sf $CODE_DIR/settings.json settings.json
		ln -sf $CODE_DIR/keybindings.json keybindings.json
		popd
	    fi
	    popd
	fi
    ;;
    Linux)
	echo "Linux detected"
    ;;
esac
