#!/bin/sh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:tlockney/dotfiles.git"

system_type=$(uname -s)

case "$(uname -s)" in
    Darwin)
	echo "MacOS detected"
	   # install homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
	    echo "Installing homebrew"
	    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
	if [ -f $HOME/.macos ]; then
	    sh $HOME/.macos
	fi
	if [ -f $HOME/.Brewfile ]; then
	    echo "Updating homebrew bundle"
	    brew bundle --global
	fi
	if [ -x $HOME/.config/Code/User ]; then
	    ln -sf $HOME/.config/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
	    ln -sf $HOME/.config/Code/User/keybindings.json $HOME/Library/Application\ Support/Code/User/keybindings.json
	    if [ -x $HOME/Library/Application\ Support/Code/User/profiles/7db57729 ]; then
		ln -sf $HOME/.config/Code/User/settings.json \
		   $HOME/Library/Application\ Support/Code/User/profiles/7db57729/settings.json
		ln -sf $HOME/.config/Code/User/keybindings.json \
		   $HOME/Library/Application\ Support/Code/User/profiles/7db57729/keybindings.json
	    fi
	fi
    ;;
    Linux)
	echo "Linux detected"
    ;;
esac
